[tool.poetry]
name = "napsy"
version = "0.1.0"
description = ""
authors = ["iJoyRide <sumfeis3@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.27.0"
fastapi = "^0.110.1"
rich = "^13.7.1"
uvicorn = "^0.29.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
